### ISSUE TITLE
make: *** [Makefile:50: setup.python] Error 1

### ISSUE THREAD

**Issue by flyingpizza** [jmeisele/fastapi-ml-scaffolding#17]
write@DESKTOP-0F4F5UI MINGW64 /i/dataEngg/git/fastapi-ml-scaffolding (master)
$ make setup
Active Python version: Python 3.9.7
Base Interpreter path: C:\Users\write\anaconda3\python.exe
Please activate python 3.6.13
make: *** [Makefile:50: setup.python] Error 1

**Comment by jmeisele** [comment]
Use pyenv to manage python envs
